[pytest]
testpaths = tests
asyncio_default_fixture_loop_scope = function

# Salida más legible
addopts = -ra --strict-markers

# Filtros de warnings ruidosos
filterwarnings =
    ignore::DeprecationWarning:dateutil.*
